azure-pkg_secrets:
  seed:
    client_id: ""
    client_secret: ""
sops:
  lastmodified: "2026-04-17T23:35:08Z"
  mac: ENC[AES256_GCM,data:pZV5W0+7srxCUXBzY7Ccq9nIEv/DBvYF/hvdPRBOaRo9UQo6SbFaYmib+MI6fb47PdVP6F0SCaeX8WgmSESOTUOLUswO2twhIPX+OQQvudVGyUzhKEjTv7Q9pBTe8TYYAUqWtPvKkhMgatQrCqRCmE1BfFSC+uKAbj8Y2B/EV0o=,iv:VEJyEySLjxyFOqXRNwBo71CuCoXT+NYRr84bAJkk2+4=,tag:JPGgCihxXs79ofzbezqDnQ==,type:str]
  pgp:
    - created_at: "2026-04-13T02:48:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMAweuHx4I2A4UAQv+L88dsS36U7itdKXbsEwvfbRQJ+EKai5tTF8Qy+DyTxy3
        1l1fUF311cyb5U/22cTQ4N2zvB879Ut30V1MXexXhl/iaPUptr60FzIpuHBMOwIu
        O9nb1AoBEnfRQDXZ8oqmDerLGWzI6qgD7GSHV8sTiaG2UWzhRvmuhoFJopVDIDJp
        LA8a9Qqv/1C2faFfEJoxtOVM+Y6htbSujFmtgq9LD557UdpylZsQu62U/bzs8mfv
        4tj47VvqLkJi7f+hsNRpW5o2R4H1YpupuDUhZWtfBW9a6zXD6i90gVpp9vnq6EZR
        Eug9/A+4G2VyLJin7YMXJAS93OKT50lHoMFuRZ2CGoE7rsh9X2FPU8quS4r7LqG9
        FIPviPsVGEpb70Pr6kaloA1w9KRLo9JFW+/Zfg3y2qOWVWkOqZ6drAY6hm+ulY6b
        IX8XrgGB23x4HnIwswegWcKxQaBPUU8gfZf3+HBOrLLdt016KLqLttMVMAZOj3xm
        khIH6pfYNq3rTeBwCeRr0lwB0J3KieSk7k61Lne+J7bCbSS+hxxb06ciFulYQF5P
        2ierWMHgavnzRKB+WwRO0j/Vhuw2KXVnMKprz2z3lwpcdJZRWzW6DG4i+YNB7Imk
        mG85dw0fJeGoCw+u8g==
        =iff/
        -----END PGP MESSAGE-----
      fp: 446B4127CF4E00C389579F20986E9FAE2FB2BEBD
    - created_at: "2026-04-13T02:48:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA1MQLyG6dlTlAQ//ZD1f6XhbfQvw1927fNhIOAwFX5mij+RLSfiIiUFTy98y
        VYAZkar418k/EXzh1cqnhsnqZg8oKYzIj+Q8+QsXjW2dZ83dAgxyPOE9TnzWzT33
        lKUwOSpSpChEz9wJBqdbAQdT4VltFw6xISmLUU8ETasA0TKNwvF2k6Cee9eqbH70
        qy4Qz6XlqFJ02VUcUTY1DzIuT+9rvb6rxQ+KRYUcMXfM5PQwbelbJQU4UC6NIKTv
        JElKyqhVxlgnEOxhP0ewKAPJvXEbu/TGxb0SF5ksE9XjYpxohm9h1XJ20YuBZHeC
        +xQjJoA6/9Cn933lyNj/b0yf5GegR15IlsQIynZMwgNGf2rc/uFanJnT6ZfkaJXk
        vQY88TsFwgAkTCLFkFKsZMgrq/x0Z38Gac6Ix9phwdo/lGqzkweQhZfLo9f9BGgo
        JQVrLWjsfyp6tvy0Zqb93OpOY9MBibg5sVrOFmWozhGB8h1WoMdneg3GFTsPxyfh
        EW1GZWIstP7SvKXArztNBs1NFebo8WE7jFGbzJE+HNlO6CsVmNz/2bV/30yWcJ1T
        x49rlSKl/a1KhFKrhp2I/KpJce7d+/5ll0rHHbmUGpGIDMpFunq48uKdZnu55Rx+
        o1FhQly+Wg63DTcKjOwH+UbsvSHykfk00nhNbunGUFWPXx2Rex0YbpgxD4zm2m/S
        XAEEkLdEQRDbG80Vq8q/UusjwgFxpkGrFBzCuMLM10NjramRUJe0Y7jLOcq1KBxK
        PlgBV+WXqiK9v8KcWaZeXOeAyjVO/9Fq6216Pb+75Dg9TdvkY1G3D5wxE28f
        =itt6
        -----END PGP MESSAGE-----
      fp: 1FAFFDF2C76C758F736178E2B776DF4CEB6B692B
  unencrypted_suffix: _unencrypted
  version: 3.10.2
